// plugins/my-calculator/src/App.tsx
import { useEffect, useState } from 'react'
import Hello from './Hello'
import Read from './Read'
import Write from './Write'
import Calculator from './Calculator'

export default function App() {
  const [enterAction, setEnterAction] = useState<any>({})
  const [route, setRoute] = useState('')

  useEffect(() => {
    // ZTools 环境检查
    if (!window.ztools) {
      console.log('ZTools not detected, running in standalone mode')
      return
    }

    window.ztools.onPluginEnter((action) => {
      setRoute(action.code)
      setEnterAction(action)
    })
    window.ztools.onPluginOut(() => {
      setRoute('')
    })
  }, [])

  if (route === 'hello') return <Hello enterAction={enterAction} />
  if (route === 'read') return <Read enterAction={enterAction} />
  if (route === 'write') return <Write enterAction={enterAction} />
  if (route === 'calculator') return <Calculator enterAction={enterAction} />

  return null
}

// plugins/variable-name/src/App.vue
<script setup>
import { onMounted, ref } from 'vue';
import Hello from './Hello/index.vue';

const route = ref('');
const enterAction = ref({});
const onEnter = ref(null);

onMounted(() => {
  window.ztools.onPluginEnter((action) => {
    route.value = action.code;
    enterAction.value = action;
    onEnter.value?.();
  });
  window.ztools.onPluginOut(() => {
    route.value = '';
  });

  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) {
      onEnter.value?.();
    }
  });
});
</script>

<template>
  <n-config-provider>
    <n-message-provider>
      <Hello
        :enter-action="enterAction"
        :on-enter="onEnter"
      />
    </n-message-provider>
  </n-config-provider>
</template>
